version: '2'

networks:
  default:

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - '.:/var/www/'
    depends_on:
      - db
    networks:
      - default

  web:
    image: nginx:1.17
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public/
    depends_on:
      - app
    ports:
      - "8050:80"
    networks:
      - default

  worker:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/www/html
    user: root
    command: ["supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    depends_on:
      - app
      - web

  db:
    image: 'bitnami/mariadb:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=lsmacox
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=app
    ports:
      - '33030:3306'
    networks:
      - default