controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


get_price:
    path: /product/get-price
    methods: POST
    controller: App\Controller\ProductController::calcPrice

payment:
    path: /product/payment
    methods: POST
    controller: App\Controller\ProductController::pay

